### ISSUE TITLE
Pitch bend range

### ISSUE THREAD

**Issue by sevonj** [sinshu/rustysynth#28] opened 2024-12-22 23:01 UTC
In some MIDI files, the pitch bend goes all over the place. I believe the issue occurs when a song changes its pitch bend range.

Here's a particularly easy to spot example, with comparison to how it sounds in rustysynth vs fluidsynth (played with VLC):

[rustysynth-pitchbend.zip](https://github.com/user-attachments/files/18223475/rustysynth-pitchbend.zip)

The relevant messages in the sample are in track 3, starting at 0x2848.

**Comment by sinshu** [comment] 2024-12-23 00:35
I have confirmed that this issue also occurs in the C# version.
It seems to be fixed in the C# version with the following change:
https://github.com/sinshu/meltysynth/commit/295638370dd99e124329312f496244b7075dc1da

If possible, I would appreciate it if you could do the following:
1. Port the above fix to rust.
2. Verify that the issue is resolved.
3. Ensure that the existing, normal playback remains unaffected.

**Comment by sevonj** [comment] 2024-12-23 12:46
Oh, I see what's going on there now. I'll start working on a PR.

**Closed as completed** 2024-12-24 00:57 UTC

**Comment by sinshu** [comment] 2024-12-24 01:12
@sevonj
I updated the library. Thanks for the PR 😁
